/**
  You need to create an express HTTP server in Node.js which will handle the logic of a todo list app.
  - Don't use any database, just store all the data in an array to store the todo list data (in-memory)
  - Hard todo: Try to save responses in files, so that even if u exit the app and run it again, the data remains (similar to databases)

  Each todo has a title and a description. The title is a string and the description is a string.
  Each todo should also get an unique autogenerated id every time it is created
  The expected API endpoints are defined below,
  1.GET /todos - Retrieve all todo items
    Description: Returns a list of all todo items.
    Response: 200 OK with an array of todo items in JSON format.
    Example: GET http://localhost:3000/todos
    
  2.GET /todos/:id - Retrieve a specific todo item by ID
    Description: Returns a specific todo item identified by its ID.
    Response: 200 OK with the todo item in JSON format if found, or 404 Not Found if not found.
    Example: GET http://localhost:3000/todos/123
    
  3. POST /todos - Create a new todo item
    Description: Creates a new todo item.
    Request Body: JSON object representing the todo item.
    Response: 201 Created with the ID of the created todo item in JSON format. eg: {id: 1}
    Example: POST http://localhost:3000/todos
    Request Body: { "title": "Buy groceries", "completed": false, description: "I should buy groceries" }
    
  4. PUT /todos/:id - Update an existing todo item by ID
    Description: Updates an existing todo item identified by its ID.
    Request Body: JSON object representing the updated todo item.
    Response: 200 OK if the todo item was found and updated, or 404 Not Found if not found.
    Example: PUT http://localhost:3000/todos/123
    Request Body: { "title": "Buy groceries", "completed": true }
    
  5. DELETE /todos/:id - Delete a todo item by ID
    Description: Deletes a todo item identified by its ID.
    Response: 200 OK if the todo item was found and deleted, or 404 Not Found if not found.
    Example: DELETE http://localhost:3000/todos/123

    - For any other route not defined in the server return 404

  Testing the server - run `npm run test-todoServer` command in terminal
 */
  const express = require('express');
  const bodyParser = require('body-parser');
  
  const app = express();
  const PORT = 3000;
  
  app.use(bodyParser.json());
  

  let todo = [{
        "id" : 1,
        "work" : "wake up at 5",
        "completed" : false
  },{
        "id" : 2,
        "work" : "brush",
        "completed" : false
  }]


app.get('/todos',(req,res)=>{
       res.status(200).json({
        "result": todo
       })  

})

app.get('/todos/:id',(req,res)=>{
        let id = Number(req.params.id);
        if(isNaN(id)){
          return res.status(400).json({message : "enter a number"});
        }
        let note = todo.find(t =>t.id === id);

        if(!note){
          return res.status(404).json({message : "todo list not found"})
        }

        res.status(200).json({
          "result" : note
        })
})



app.post('/todos',(req,res)=>{
      let {work,completed} = req.body;

      if(typeof work !== "string" || work.trim() === ""){
        return res.status(400).send("work must be a non-empty string!")
      }

      let newarray = {
        "id" : todo.length + 1,
        "work" : work,
        "completed" : completed ?? false
      }
      todo.push(newarray);
      res.status(200).send(todo); 
      
})


app.put('/todos/put/:id',(req,res)=>{
      let id = Number(req.params.id);

      if(isNaN(id)){
        return res.json({
         message: "invalid id "  
            })
      }
      
      let todoindex = todo.find(t=> t.id === id);   //todoindex is not a seperate todo. its a reference/pointer to the original array todo. so changes in it means we r changing actual todo list

      if(todoindex === undefined){
        return res.status(404).send("todo list not found")
      }

      let {work , completed} = req.body;
      
      if(work !== undefined){
          if(typeof work !== "string" || work.trim() === "" ){
           return res.status(400).send("invalid input as work")
          }
          todoindex.work = req.body.work;
      }
      
      if(completed !== undefined){
          if(typeof completed !== "boolean"){
           return res.status(400).send("complete must be boolean")
          }
          todoindex.completed = req.body.completed;
      }
      
      res.json({
        message : "your work has been done",
        result : todo
      })   
})




app.delete('/todos/del/:id',(req,res)=>{

  let id = Number(req.params.id);

  if(isNaN(id)){
        return res.json({
         message: "invalid id "  
            })
      }


  let indexrefernce = todo.findIndex(t=>t.id === id);

  if(indexrefernce === -1){
    return res.json({
      message : "index not found"
    })
  }

  todo.splice(indexrefernce,1);

  res.status(200).json({
    message : "operation has been done",
    message : todo
  })

})



app.listen(PORT,()=>{
  console.log(`server is running ${PORT}`);
});


  module.exports = app;